#!/usr/bin/env bash
set -eo pipefail

# Same reason as dx-theme-restore: Herdr restores OSC defaults as soon as a
# short-lived child command exits, so a `dx-theme <name>` run inside a pane
# must go through the writer, which targets the attached client's host TTY.
# The writer resolves the palette from these same Tinty hook variables.
if [ "${HERDR_ENV:-}" = 1 ] || [ -n "${HERDR_PANE_ID:-}" ]; then
  exec "$HOME/.local/bin/dx-theme-write-tool-themes"
fi

base00="$TINTY_SCHEME_PALETTE_BASE00_HEX_R$TINTY_SCHEME_PALETTE_BASE00_HEX_G$TINTY_SCHEME_PALETTE_BASE00_HEX_B"
base01="$TINTY_SCHEME_PALETTE_BASE01_HEX_R$TINTY_SCHEME_PALETTE_BASE01_HEX_G$TINTY_SCHEME_PALETTE_BASE01_HEX_B"
base02="$TINTY_SCHEME_PALETTE_BASE02_HEX_R$TINTY_SCHEME_PALETTE_BASE02_HEX_G$TINTY_SCHEME_PALETTE_BASE02_HEX_B"
base03="$TINTY_SCHEME_PALETTE_BASE03_HEX_R$TINTY_SCHEME_PALETTE_BASE03_HEX_G$TINTY_SCHEME_PALETTE_BASE03_HEX_B"
base04="$TINTY_SCHEME_PALETTE_BASE04_HEX_R$TINTY_SCHEME_PALETTE_BASE04_HEX_G$TINTY_SCHEME_PALETTE_BASE04_HEX_B"
base05="$TINTY_SCHEME_PALETTE_BASE05_HEX_R$TINTY_SCHEME_PALETTE_BASE05_HEX_G$TINTY_SCHEME_PALETTE_BASE05_HEX_B"
base06="$TINTY_SCHEME_PALETTE_BASE06_HEX_R$TINTY_SCHEME_PALETTE_BASE06_HEX_G$TINTY_SCHEME_PALETTE_BASE06_HEX_B"
base07="$TINTY_SCHEME_PALETTE_BASE07_HEX_R$TINTY_SCHEME_PALETTE_BASE07_HEX_G$TINTY_SCHEME_PALETTE_BASE07_HEX_B"
base08="$TINTY_SCHEME_PALETTE_BASE08_HEX_R$TINTY_SCHEME_PALETTE_BASE08_HEX_G$TINTY_SCHEME_PALETTE_BASE08_HEX_B"
base09="$TINTY_SCHEME_PALETTE_BASE09_HEX_R$TINTY_SCHEME_PALETTE_BASE09_HEX_G$TINTY_SCHEME_PALETTE_BASE09_HEX_B"
base0A="$TINTY_SCHEME_PALETTE_BASE0A_HEX_R$TINTY_SCHEME_PALETTE_BASE0A_HEX_G$TINTY_SCHEME_PALETTE_BASE0A_HEX_B"
base0B="$TINTY_SCHEME_PALETTE_BASE0B_HEX_R$TINTY_SCHEME_PALETTE_BASE0B_HEX_G$TINTY_SCHEME_PALETTE_BASE0B_HEX_B"
base0C="$TINTY_SCHEME_PALETTE_BASE0C_HEX_R$TINTY_SCHEME_PALETTE_BASE0C_HEX_G$TINTY_SCHEME_PALETTE_BASE0C_HEX_B"
base0D="$TINTY_SCHEME_PALETTE_BASE0D_HEX_R$TINTY_SCHEME_PALETTE_BASE0D_HEX_G$TINTY_SCHEME_PALETTE_BASE0D_HEX_B"
base0E="$TINTY_SCHEME_PALETTE_BASE0E_HEX_R$TINTY_SCHEME_PALETTE_BASE0E_HEX_G$TINTY_SCHEME_PALETTE_BASE0E_HEX_B"
base0F="$TINTY_SCHEME_PALETTE_BASE0F_HEX_R$TINTY_SCHEME_PALETTE_BASE0F_HEX_G$TINTY_SCHEME_PALETTE_BASE0F_HEX_B"

if [ -z "$base00" ] || [ -z "$base05" ]; then
  exit 0
fi

home_dir="$HOME"
if [ -z "$home_dir" ]; then
  home_dir="/home/dx"
fi

emit_osc() {
  code="$1"
  color="$2"
  if [ -n "$TMUX" ]; then
    printf '\033Ptmux;\033\033]%s;#%s\033\\\033\\' "$code" "$color"
  else
    printf '\033]%s;#%s\033\\' "$code" "$color"
  fi
}

emit_osc 10 "$base05"
emit_osc 11 "$base00"

if [ -x "$home_dir/.local/bin/dx-theme-write-tool-themes" ]; then
  "$home_dir/.local/bin/dx-theme-write-tool-themes" \
    "$base00" "$base01" "$base02" "$base03" "$base04" "$base05" "$base06" "$base07" \
    "$base08" "$base09" "$base0A" "$base0B" "$base0C" "$base0D" "$base0E" "$base0F" || true
fi